### ISSUE TITLE
ContentType is not correctly positionned

### ISSUE THREAD

**Issue by pulse-mind** [fdemmer/django-weasyprint#17]
Whe I use Firefox and Debug tool I can see that the content type is HTML:

Content-Type | text/html; charset=utf-8

**Comment by pulse-mind** [comment]
To try, I added
`self['Content-type'] = CONTENT_TYPE_PDF`
after
```
 if filename:
            self['Content-Disposition'] = '{}filename="{}"'.format(
                'attachment;' if attachment else 'inline;',
                filename,
            )
```

And it works better

**Comment by pulse-mind** [comment]
or 
`self['Content-type'] = content_type`

**Comment by fdemmer** [comment]
If you are using `WeasyTemplateResponseMixin` on the view, the the content type is set. This would also be the place to configure `CONTENT_TYPE_PNG` instead of `CONTENT_TYPE_PDF`, eg:

    class ImageDetailView(WeasyTemplateResponseMixin, DetailView):
        content_type = CONTENT_TYPE_PNG

If you use `WeasyTemplateResponse` directly it is up to you to set the proper content type of the response; `content_type` is a kwarg of Django's [`HttpResponseBase`](https://docs.djangoproject.com/en/2.0/_modules/django/http/response/).
