### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by pvandriessche** [fdemmer/django-weasyprint#37]
I'm trying to render an html template with some images.
It works fine as a normal template view. Then I see the images.
But when I try to make the PDF they are not showing. I'm using the basic code from the example
``` 
class MyModelView(DetailView):
     # vanilla Django DetailView
     model = Factuur
     template_name = 'facturatie/pdf.html'

   
class MyModelPrintView(WeasyTemplateResponseMixin, MyModelView):
    # show pdf in-line (default: True, show download dialog)
    pdf_attachment = False
    # custom response class to configure url-fetcher
    response_class = WeasyTemplateResponse
```

In my template

```
  {% load static%}
  ...
  <img src="{%static '/facturatie/logo.png' %}" alt="logo" />

```
Did anyone experience this before?

**Comment by fdemmer** [comment]
`WeasyTemplateResponse` uses the [django_url_fetcher](https://github.com/fdemmer/django-weasyprint/blob/master/django_weasyprint/utils.py#L11) which uses Django's [`staticfiles` finder](https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#finders-module). Try setting breakpoints in there to see what exactly fails.

**Comment by hrekov** [comment]
@fdemmer i have the same problem but only in a docker container. It tries to fetch resources with outer port inside container
For example i have the following port mappings:
8008(host) 8000(container), but when i output url it receives url with the 8008 instead of 8000 inside container

**Comment by fdemmer** [comment]
@Alexander-Greckov 

The URL-fetcher provided by _this_ library only handles URLs starting with `file://`! Everything else is forwarded to [the default provided by weasyprint](https://weasyprint.readthedocs.io/en/stable/api.html#weasyprint.default_url_fetcher).

If you don't use `file://` URLs the problem is possibly somewhere else...

- Do you use the the `{% static %}` template tag or hardcoded paths or URLs?
- How do you use the `static` tag? (@pvandriessche uses an absolute path starting with a `/`, which is usually wrong)
- Did you override the default `STATIC_URL` setting? What is it?

If you think the [`{% static %}` template tag](https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#std:templatetag-static) produces the wrong URL, this is not a django-weasyprint issue. However I'd expect it to use port 8008 in your case, since that is where the HTTP request came from. Maybe look into what the [static files storage](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-STATICFILES_STORAGE) does (because, quoting Django docs: "the tag will serve files using url() method of the storage specified by `STATICFILES_STORAGE`").

I'd appreciate it if you (or anyone) could come up with a test procedure to reproduce this problem. There are already some tests for the URL-fetcher in [test_utils.py](https://github.com/fdemmer/django-weasyprint/blob/master/django_weasyprint/tests/test_utils.py).

**Comment by hrekov** [comment]
@fdemmer I resolved this issue with the WEASYPRINT_BASEURL option. Thanks!

**Comment by HenryMehta** [comment]
I am also getting this issue with media images.  Running locally with a virtualenv everything works fine, but when I deploy to AWS Elastic Beanstalk the images no longer show (or rather show inconsistently because sometimes the last couple are displayed).

I am using the same static and media files in both the local and AWS environments (ie AWS S3).  My media storage is defined as

```
class MediaStorage(S3Boto3Storage):
    """
    This is our default storage backend for all media in the system.

    DEFAULT_FILE_STORAGE expects a class and not an instance
    """

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('file_overwrite', False)
        kwargs.setdefault('url_protocol', 'https:')
        kwargs.setdefault('querystring_auth', False)
        kwargs.setdefault('location', get_storage_env('media'))
        kwargs.setdefault('default_acl', 'public-read')
        kwargs.setdefault('object_parameters', {
            'CacheControl': 'max-age=31536000'
        })
        super(MediaStorage, self).__init__(*args, **kwargs)

    def _save_content(self, obj, content, parameters):
        """
        We create a clone of the content file as when this is passed to boto3 it wrongly closes
        the file upon upload where as the storage backend expects it to still be open
        """
        # Seek our content back to the start
        content.seek(0, os.SEEK_SET)

        # Create a temporary file that will write to disk after a specified size
        content_autoclose = SpooledTemporaryFile()

        # Write our original content into our copy that will be closed by boto3
        content_autoclose.write(content.read())

        # Upload the object which will auto close the content_autoclose instance
        super(MediaStorage, self)._save_content(obj, content_autoclose, parameters)

        # Cleanup if this is fixed upstream our duplicate should always close
        if not content_autoclose.closed:
            content_autoclose.close()
```
My view is 

```
class ReportPDF (IsStaffMixin, WeasyTemplateResponseMixin, DetailView):
#class ReportPDF (IsStaffMixin, DetailView):
    model = Report
    template_name = "monaco/report_pdf.html"
    #content_type = CONTENT_TYPE_PNG

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if len(self.object.search_area.all()) > 0:
            pc = self.object.search_area.all()[0]
            ctx['lat_lng'] = lat_lng_locator(pc.post_code)
        return ctx
```

**Comment by HenryMehta** [comment]
And I've just found older posts showing the issue is AWS Elastic Beanstalk isn't loading `GDK-PixBuf`.  Not got it working yet but know what I need to do
