### ISSUE TITLE
text overlaps when using intcoma template filter

### ISSUE THREAD

**Issue by keinagae** [fdemmer/django-weasyprint#46]
if i try to print invoice without filter its working fine like 
![Screenshot 2021-01-11 131256](https://user-images.githubusercontent.com/43607374/104158380-121c0180-540f-11eb-9964-8aaa920c4032.jpg)

but when i try to add comas with intcoma filter whole text starts overlap eachother like this 
![Screenshot 2021-01-11 131349](https://user-images.githubusercontent.com/43607374/104158458-35df4780-540f-11eb-83ec-339455342c97.jpg)

i think it may be because of text over flow any idea on how to solve it

**Comment by fdemmer** [comment]
sorry, i don't think i can help... this is almost certainly not an issue with django-weasyprint and only _maybe_ with weasyprint itself. what you could try:

- check the html output, that is used to generate the pdf. maybe this is not related to the pdf generation at all if the problem is already in the input.
- it is strange, that you mention using the `incoma` filter, but the texts "Date:", "Supplier:", ... at the bottom where i assume you dont use it, are also broken.
- maybe there is css, that causes this, when the page is too narrow
