### ISSUE TITLE
Manifest-suffixed image not showing up

### ISSUE THREAD

**Issue by niccolomineo** [fdemmer/django-weasyprint#48]
Hi, apparently a static image cannot be displayed with the standard `static` template tag when using a manifest-appending storage.

The issue seems to be in `utils.django_url_fetcher:34`, where `find()` is invoked: file finders are not able to find the manifest file, because `STATIC_ROOT` does not and cannot appear in `STATICFILES_FINDERS` at the same time.

A temporary workaround is to hardcode the file path with the prepended static root inside the template file.

I would like to propose a couple of alternative solutions:

#49 does not remove the current finding behaviour, but simply checks whether the collected file exists.

#50 Only performs said check ('cause is it really needed to trigger the finders in the first place?)

**Comment by n1ngu** [comment]
Pretty much related: #47

**Comment by fdemmer** [comment]
Thank you for bringing this up and already thinking of solutions! It's somewhat related to #47, but also very different :)

My notes from analyzing the problem; scenario and settings:
- `STATICFILES_STORAGE = ...ManifestStaticFilesStorage`
- `STATIC_URL = '/static/'`
- `WEASYPRINT_BASEURL` is **not** set!
- in a template use `{% static 'css/main.css' %}`
- runserver on localhost
- `django_url_fetcher()` receives `http://localhost:8000/static/css/main.95fde747c1c3.css`
- ... since `django_url_fetcher()` only deals with `file://` URLs, it does nothing, the file is fetched via http (which "works", but obviously is not ideal and only, if there is actually something serving the file at that URL).

Same settings as above, but:
- `WEASYPRINT_BASEURL = ''`
- `django_url_fetcher()` receives `file:///static/css/main.95fde747c1c3.css`
- ... that matches the required `file://` prefix for using a local file, but as you pointed out Django's file-finders are built to find `main.css` in [`STATICFILES_DIRS`  or `static` subdirectories in each app](https://docs.djangoproject.com/en/3.2/ref/settings/#staticfiles-finders) and _not_ in `STATIC_ROOT` after being collected.

The idea behind using the file-finders in the URL-fetcher was, that one does _not need_ to run `collectstatic` to be able to use static files. With `ManifestStaticFilesStorage` the URL-fetcher gets the "wrong" filename to "find" that way.

I am going to think further on this... your suggested PRs are possibilities, I am just not sure yet if I want to go around opening files just like that :) ... my current idea/approach would be a "reverse manifest lookup" to find the files' original names.

**Comment by niccolomineo** [comment]
Hi, any updates on this?

**Comment by fdemmer** [comment]
Allright, put something together... went for the "reverse manifest lookup" solution... maybe you can try it out? It's in the [develop](https://github.com/fdemmer/django-weasyprint/compare/develop) branch.

It should work with the second scenario described before:
- In a template use `{% static 'css/main.css' %}`
   - There should be absolute paths with the configured `STATIC_URL` in the HTML.
- Add `WEASYPRINT_BASEURL = ''` or `WEASYPRINT_BASEURL = '/'` to your `settings`.
  - WeasyPrint [converts `''` to _the current directory of the process_](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/urls.py#L82) using [os.path.abspath()](https://docs.python.org/3/library/os.path.html#os.path.abspath), so using `'/'` is probably the safer practice. The end-result is the same as long as the asset paths are absolute (i.e. start with a `/`), because of how [os.path.join() works with absolute paths](https://docs.python.org/3/library/os.path.html#os.path.join).
  - This disables automatically providing the [`base_url` based on the `request`](https://github.com/fdemmer/django-weasyprint/blob/main/django_weasyprint/views.py#L26) by django-weasyprint.
  - WeasyPrint will [prefix any path that does not "look like an URL" with "file://"](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/urls.py#L69).
  - And that causes `django_url_fetcher()` to try to [find the original name from the hashed one](https://github.com/fdemmer/django-weasyprint/compare/develop#diff-3c92cce0ebd2c271b5b9731e152fa968e97beb1839f0031a88352edb702e693aR50) in an attempt to find those files in the filesystem via `staticfiles` finder.
- It is necessary to run `collectstatic` to generate the `staticfiles.json` manifest to look up the filename!

**Comment by niccolomineo** [comment]
At last, I was able to try it on a pet project and it seems to run fine. Thanks!
