### ISSUE TITLE
Module dus not allow to download images that need authentication

### ISSUE THREAD

**Issue by vdveldet** [fdemmer/django-weasyprint#60]
When building a pdf on a site that has everything authenticated, the images requested are redirected to login.
It should be possible to add authentication information to the weasyprint in order to enter the site as an authenticated user.

**Comment by fdemmer** [comment]
It is possible to extend or completely replace the "url_fetcher". Please see the [README](https://github.com/fdemmer/django-weasyprint/tree/develop#example) for examples.

What to do exactly in your case depends on what "has everything authenticated" exactly means in technical terms. In the end the _server_ has to make requests to fetch assets for the PDF, not the _client_ which probably holds the authenticated session in a cookie or something.

If the images you mentioned are stored on the same server, you might be able to force loading from the filesystem instead of HTTP requests by disabling the [automatic `base_url` configuration by setting `WEASYPRINT_BASEURL = '/'`](https://github.com/fdemmer/django-weasyprint/tree/develop#settings)
